[package]
name = "vkrs"
version = "0.1.0"
authors = ["Konstantin Stepanov <me@kstep.me>"]
description = "Vkontakte Rust client library"
license = "MIT"
repository = "https://github.com/kstep/vkrs"
keywords = ["vk", "api"]

[dependencies]
url = "*"
hyper = "*"
serde = "*"
serde_macros = "*"
serde_json = "*"

clap = "*"
