[package]
authors = ["Konstantin Stepanov <me@kstep.me>"]
build = "build.rs"
description = "Vkontakte Rust client library"
keywords = ["vk", "api"]
license = "MIT"
name = "vkrs"
repository = "https://github.com/kstep/vkrs"
version = "0.2.0"

[build-dependencies]

[build-dependencies.serde_codegen]
optional = true
version = "0.6.11"

[build-dependencies.syntex]
optional = true
version = "0.26.0"

[dependencies]
chrono = "0.2.18"
clap = "^1.5.4"
hyper = "^0.7.1"
inth-oauth2 = "0.5.1"
rustc-serialize = "0.3.16"
serde = "^0.6.6"
serde_json = "^0.6.0"
url = "^0.5.2"

[dependencies.serde_macros]
optional = true
version = "^0.6.5"

[features]
default = ["serde_codegen", "syntex"]
nightly = ["serde_macros"]
